### ISSUE TITLE
Sorting from the highest

### ISSUE THREAD

**Issue by isaacfromhxm** [desandro/colcade#6]
First of all I am very satisfy with the results provided by colcade. It is a very nice layout. However I am having one issue where the sorting of items are in vertical order. I managed to display all the images, on top of the images I use a image gallery modal. The next image will go through vertically instead of horizontally. How do I custom sort the image? If it is possible. Thank you~

**Comment by desandro** [comment]
Sorry, this won't work with Colcade. You may have to use [Masonry](http://masonry.desandro.com) instead. Colcade works by re-ordering items in the DOM.

**Comment by isaacfromhxm** [comment]
Thank you Desandro, appreciated your feedback :)

**Comment by isaacfromhxm** [comment]
Hi DeSandro,

My apologize if I had bothered you. Just want to share with you my website
which make use of your colcade.
Here https://www.hungryxmore.com/FoodNearby.php. It uses your colcade to
display the foods with a few information.
I would like to know what do you think because your work are amazing and
you benefited us :)

**Comment by desandro** [comment]
This is great use! Thanks so much for sharing :)
